#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OrariUnibg.Droid.Resource", IsApplication=true)]

namespace OrariUnibg.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::OrariUnibg.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::OrariUnibg.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int blue = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int lightblue = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int semitranspwhite = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int transparent = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int white = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_clock = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_completo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_esami = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_next = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_sync = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int LogoUnibg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int selectable_background_example = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tab_bar_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tab_bar_background_selected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int tab_bar_background_selected_pressed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int tab_bar_text = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int UnibgOk = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int splash_layout = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int splash_layout = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int ActionBarCustomHeader = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int ActionBarCustomTabBarStyle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int ActionBarCustomTabStyle = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int ActionBarCustomTabTextStyle = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
