#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OrariUnibg.Droid.Resource", IsApplication=true)]

namespace OrariUnibg.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::OrariUnibg.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::OrariUnibg.Droid.Resource.String.Hello;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.error = global::OrariUnibg.Droid.Resource.Drawable.error;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.info = global::OrariUnibg.Droid.Resource.Drawable.info;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.success = global::OrariUnibg.Droid.Resource.Drawable.success;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.warning = global::OrariUnibg.Droid.Resource.Drawable.warning;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.desc = global::OrariUnibg.Droid.Resource.Id.desc;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.image = global::OrariUnibg.Droid.Resource.Id.image;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.title = global::OrariUnibg.Droid.Resource.Id.title;
			global::Toasts.Forms.Plugin.Droid.Resource.Layout.crouton = global::OrariUnibg.Droid.Resource.Layout.crouton;
			global::Toasts.Forms.Plugin.Droid.Resource.String.ApplicationName = global::OrariUnibg.Droid.Resource.String.ApplicationName;
			global::Toasts.Forms.Plugin.Droid.Resource.String.Hello = global::OrariUnibg.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::OrariUnibg.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::OrariUnibg.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050007
			public const int accent = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int blue = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int lightblue = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int material_blue_500 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int material_blue_700 = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int semitranspwhite = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int transparent = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int white = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int error = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_bin = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_clock = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_clock_blue = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_clock_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_completo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_completo_blue = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_completo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_esami = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_home = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_home_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_home_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_launcher = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_menu = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_next = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_nostar = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_notification_school = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_settings_blue = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_settings_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_settings_gray = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_star = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_sync = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int info = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int LogoUnibg = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Screen1 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Screen2 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int selectable_background_example = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int splash = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int success = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int tab_bar_background = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int tab_bar_background_selected = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tab_bar_background_selected_pressed = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_bar_text = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int UnibgOk = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int warning = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int desc = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int image = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int splash_layout = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int title = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int crouton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int splash_layout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int MyTheme = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int MyTheme_ = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int MyTheme_ActionBar_TabBarStyle = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int MyTheme_ActionBar_TabStyle = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int MyTheme_ActionBar_TabTextStyle = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int MyTheme_ActionBar_TitleTextStyle = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int MyTheme_ActionBarStyle = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int MyTheme_ActionModeStyle = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_Base = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
